---
- name: Check server uptime
  hosts: all
  gather_facts: false

  tasks:
    - name: Get server uptime
      ansible.builtin.command:
        cmd: uptime
      register: uptime_result
      changed_when: false

    - name: Display server uptime
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: {{ uptime_result.stdout }}"
