---
- name: Check server uptime
  hosts: all
  gather_facts: true

  tasks:
    - name: Get server uptime
      ansible.builtin.command:
        cmd: uptime
      register: uptime_result
      changed_when: false

    - name: Display server information
      ansible.builtin.debug:
        msg: >-
          {{ inventory_hostname }}
          | {{ ansible_distribution }} {{ ansible_distribution_version }}
          | {{ ansible_architecture }}
          | uptime: {{ uptime_result.stdout }}
